# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# labels to be used with /area command
area:
  - 'gcp'
  - 'aws'
  - 'azure'
  - 'kubernetes'

kind:
  - 'documentation'
  - 'discussion'
  - 'feature'
  - 'question'

priority:
  - 'low'
  - 'medium'
  - 'high'
  - 'critical'

status:
  - available
  - blocked
  - in_progress
  - on_hold

# File globs for PR labeler
# tests:
#   - '**/*.test.ts'

'area/kubernetes':
  - kubernetes/*
  - kubernetes/**/*

'area/gcp':
  - iac/gcp/*
  - iac/gcp/**/*

'area/aws':
  - iac/aws/*
  - iac/aws/**/*

'area/azure':
  - iac/azure/*
  - iac/azure/**/*

'kind/documentation':
  - docs/*
  - docs/**/*
