# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.4
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
      files: \.tf$
      args:
      - '--args=--enable-rule=terraform_deprecated_interpolation'
      - '--args=--enable-rule=terraform_deprecated_index'
      - '--args=--enable-rule=terraform_unused_declarations'
      - '--args=--enable-rule=terraform_comment_syntax'
      - '--args=--enable-rule=terraform_documented_outputs'
      - '--args=--enable-rule=terraform_documented_variables'
      - '--args=--enable-rule=terraform_typed_variables'
      - '--args=--enable-rule=terraform_naming_convention'
      - '--args=--enable-rule=terraform_required_version'
      - '--args=--enable-rule=terraform_required_providers'
      - '--args=--enable-rule=terraform_unused_required_providers'
      - '--args=--enable-rule=terraform_standard_module_structure'
    - id: terraform_trivy
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: insert-license
    files: (\.yaml|\.yml|\.tf)
    exclude: ^\.secrets/.*$|^\.git-crypt/.*$
    args:
    - --license-filepath
    - hack/config/LICENSE
    # - --remove-header
