# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
name: Project / Draft PR Labels

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: label swapping
      uses: jinmayamashita/ready-for-review@1.0.0
      with:
        in-progress-label: 'status/in_progress'
        ready-for-review-label: 'status/review_needed'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
