---
name: Terraform / Build

on:
  pull_request:
    paths:
      - modules/**

permissions:
  contents: read

jobs:
  validation:
    name: Terraform Validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - adot
          - amg
          - amp
          - cloudwatch
          - grafana
          - loki
          - mimir
          - prometheus
          - tempo
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ matrix.module }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.module }}

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ${{ matrix.module }}
